#!/bin/bash

set -o nounset -o pipefail -o errexit
set -o xtrace

SCRIPT_DIR=$(readlink -f "$0" | xargs dirname)

SESSION=${SESSION-stream}
ACTION=${1-start}

if [ "$ACTION" = "start" ]; then
    tmux new-session -A -s "$SESSION" "$0" setup
elif [ "$ACTION" = "setup" ]; then
    echo "setting up..."
    tmux new-window -n "restreamer" "$SCRIPT_DIR/restreamer"
    while sleep 1; do
        echo "done..."
    done
fi
