#!/bin/bash

set -o nounset -o pipefail -o errexit

SCRIPT_DIR=$(readlink -f "$0" | xargs dirname)

export TITLE_FILE=$SCRIPT_DIR/.currently-playing.title
export LINK_FILE=$SCRIPT_DIR/.currently-playing.link

rm -f "$TITLE_FILE" "$LINK_FILE"

${MPV-/usr/bin/mpv} --script="$SCRIPT_DIR/currently-playing.lua" "$@"
